<?php
/**
 * Created by PhpStorm.
 * User: zhanghongbo
 * Date: 2019/3/12
 * Time: 下午3:24
 */

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'Anlewo\ApiView\controllers';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}