<?php
/**
 * Created by PhpStorm.
 * User: zhanghongbo
 * Date: 2019/3/12
 * Time: 下午3:24
 */
namespace Anlewo\ApiView;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'Anlewo\ApiView\controllers';

    public $apiConfig = [];

    public $apiHost = '';

    public $defaultVersion = 'v1';

    public $docTitle = "安乐窝接口文档中心";
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}